//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_partner
    {
        public decimal Partner { get; set; }
        public string Proizvoditel { get; set; }
        public int default_percent { get; set; }
        public bool isDefault { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual partner partner1 { get; set; }
        public virtual Proizvoditel Proizvoditel1 { get; set; }
    }
}
