//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document()
        {
            this.document_detail = new HashSet<document_detail>();
            this.stokas = new HashSet<stoka>();
        }
    
        public decimal doc_nomer { get; set; }
        public byte type { get; set; }
        public decimal nomer { get; set; }
        public bool payed { get; set; }
        public Nullable<System.DateTime> data_payed { get; set; }
        public decimal partner { get; set; }
        public Nullable<decimal> tek_percent { get; set; }
        public System.DateTime data { get; set; }
        public string izdal { get; set; }
        public System.Guid rowguid { get; set; }
        public bool isPrinted { get; set; }
        public bool isChecked { get; set; }
        public string zabelezka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document_detail> document_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stoka> stokas { get; set; }
    }
}
