//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_detail
    {
        public decimal id { get; set; }
        public decimal doc_nomer { get; set; }
        public decimal Debit { get; set; }
        public decimal Kredit { get; set; }
        public decimal Dost_price { get; set; }
        public bool IsKons { get; set; }
        public decimal dost_price1 { get; set; }
        public byte lastpercent { get; set; }
        public System.Guid rowguid { get; set; }
        public string artInfo { get; set; }
    
        public virtual artikul artikul { get; set; }
        public virtual document document { get; set; }
    }
}
