//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogovor_dost
    {
        public decimal dogovor { get; set; }
        public decimal nomer { get; set; }
        public Nullable<decimal> id { get; set; }
        public Nullable<int> kat { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_to_plat { get; set; }
        public Nullable<bool> pay { get; set; }
        public Nullable<bool> Back { get; set; }
        public Nullable<System.DateTime> data_get { get; set; }
        public Nullable<System.DateTime> data_pay { get; set; }
        public Nullable<System.DateTime> data_back { get; set; }
        public Nullable<decimal> dok_order { get; set; }
        public string Artikul { get; set; }
    }
}
