//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class podvid
    {
        public string vid { get; set; }
        public string podvid1 { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual vid vid1 { get; set; }
    }
}
