//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public decimal id { get; set; }
        public Nullable<decimal> price1 { get; set; }
        public string obect { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual artikul artikul { get; set; }
        public virtual obect obect1 { get; set; }
    }
}
