//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvoditel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvoditel()
        {
            this.Default_partner = new HashSet<Default_partner>();
        }
    
        public string Proizvoditel1 { get; set; }
        public byte def_percent { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Default_partner> Default_partner { get; set; }
        public virtual Proizvoditel Proizvoditel11 { get; set; }
        public virtual Proizvoditel Proizvoditel2 { get; set; }
    }
}
