//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class revizia
    {
        public decimal id { get; set; }
        public Nullable<int> kol { get; set; }
        public System.DateTime data { get; set; }
        public string obect { get; set; }
        public Nullable<int> computer { get; set; }
        public string position { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
