//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class stoka
    {
        public decimal id { get; set; }
        public decimal doc_number { get; set; }
        public string obect { get; set; }
        public int debit { get; set; }
        public int kredit { get; set; }
        public decimal price { get; set; }
        public string artikul_info { get; set; }
        public decimal dost_price { get; set; }
        public System.Guid uniqueID { get; set; }
        public System.Guid rowguid { get; set; }
        public decimal nomerInDogovor { get; set; }
    
        public virtual artikul artikul { get; set; }
        public virtual document document { get; set; }
    }
}
